server:
  port: 8083

spring:
  application:
    name: 3.customer
  cloud:
    config:
      uri: http://localhost:8084
      username: root
      password: root

#server:
  #port: 8083

#spring:
  #application:
    #name: Customer-Client
  #data:
    #mongodb:
      #uri: mongodb://localhost:27017/customer